import type { Metadata } from "next";
import { Inter } from "next/font/google";

import { acceptedLocales } from "@/utils/api/getLocale";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Proyectos - Falsa Escuadra Estudio",
    description: "Generated by create next app",
    robots: "noindex",
};

export default async function ProjectsLayout({
    children,
    params: { lang },
}: {
    children: React.ReactNode;
    params: { lang: (typeof acceptedLocales)[number] };
}) {
    return <>{children}</>;
}
