import type { Metadata } from "next";
import { Inter } from "next/font/google";

import { acceptedLocales } from "@/utils/api/getLocale";
import { NavbarContainer } from "@/containers/NavbarContainer/NavbarContainer";
import { SearchBoxContainer } from "@/containers/SearchBoxContainer/SearchBoxContainer";
import { FooterComponent } from "@/components/FooterComponent/FooterComponent";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Proyectos - Falsa Escuadra Estudio",
    description: "Generated by create next app",
    robots: "noindex",
};

export default async function ProjectsLayout({
    children,
    params: { lang },
}: {
    children: React.ReactNode;
    params: { lang: (typeof acceptedLocales)[number] };
}) {
    return (
        <>
            <NavbarContainer>
                <SearchBoxContainer />
            </NavbarContainer>
            {children}
            <FooterComponent />
        </>
    );
}
