import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { SessionProvider } from "next-auth/react";
import { getServerSession } from "next-auth";
import { authOptions } from "@/utils/auth/authOptions";
import Provider from "./context/sessionProvider";
import { ReduxProvider } from "@/redux/provider";
import { notFound } from "next/navigation";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Falsa Escuadra Estudio",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    const session = await getServerSession(authOptions);
    return (
        <Provider session={session}>
            <html lang="en">
                <body className={inter.className}>
                    <ReduxProvider>{children}</ReduxProvider>
                </body>
            </html>
        </Provider>
    );
}
