import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { SessionProvider } from "next-auth/react";
import { getServerSession } from "next-auth";
import { authOptions } from "@/utils/auth/authOptions";
import Provider from "./context/sessionProvider";
import { ReduxProvider } from "@/redux/provider";
import { notFound } from "next/navigation";
import { store } from "@/redux/store";
import { setLanguage } from "@/redux/features/siteTexts-slice";
import { LanguageProvider } from "@/context/languageProvider";
import { acceptedLocales } from "@/middleware";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Falsa Escuadra Estudio",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
    params: { lang },
}: {
    children: React.ReactNode;
    params: { lang: (typeof acceptedLocales)[number] };
}) {
    const session = await getServerSession(authOptions);
    console.log("[LANG]", lang);

    return (
        <Provider session={session}>
            <html lang="en">
                <body className={inter.className}>
                    <ReduxProvider>
                        <LanguageProvider lang={lang}>
                            {children}
                        </LanguageProvider>
                    </ReduxProvider>
                </body>
            </html>
        </Provider>
    );
}
